export const GET_BUS_PASS_REQS = "GET_BUS_PASS_REQS"
export const GET_BUS_APPROVED_PASS_REQ = "GET_BUS_APPROVED_PASS_REQ"
export const CLEAR_BUS_PASS_REQS = "CLEAR_BUS_PASS_REQS"
export const CLEAR_BUS_APPROVED_PASS_REQS = "CLEAR_BUS_APPROVED_PASS_REQS"