export const GET_TRAIN_PASS_REQS = "GET_TRAIN_PASS_REQS"
export const GET_TRAIN_APPROVED_PASS_REQ = "GET_TRAIN_APPROVED_PASS_REQ"
export const CLEAR_TRAIN_PASS_REQS = "CLEAR_TRAIN_PASS_REQS"
export const CLEAR_TRAIN_APPROVED_PASS_REQS = "CLEAR_TRAIN_APPROVED_PASS_REQS"