export const SAVE_USER_INFO = "SAVE_USER_IN"
export const CLEAR_USER_INFO = "CLEAR_USER_INFO"
export const USER_PROFILE_INFO = "USER_PROFILE_INFO"
export const CLAER_USER_PROFILE_INFO = "CLAER_USER_PROFILE_INFO"